# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='simple',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csimple.proto\x12\x06simple\"%\n\x07TestMsg\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t29\n\x0bTestService\x12*\n\x04test\x12\x0f.simple.TestMsg\x1a\x0f.simple.TestMsg\"\x00\x62\x06proto3')
)




_TESTMSG = _descriptor.Descriptor(
  name='TestMsg',
  full_name='simple.TestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='simple.TestMsg.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='simple.TestMsg.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['TestMsg'] = _TESTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestMsg = _reflection.GeneratedProtocolMessageType('TestMsg', (_message.Message,), dict(
  DESCRIPTOR = _TESTMSG,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.TestMsg)
  ))
_sym_db.RegisterMessage(TestMsg)



_TESTSERVICE = _descriptor.ServiceDescriptor(
  name='TestService',
  full_name='simple.TestService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=63,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='test',
    full_name='simple.TestService.test',
    index=0,
    containing_service=None,
    input_type=_TESTMSG,
    output_type=_TESTMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTSERVICE)

DESCRIPTOR.services_by_name['TestService'] = _TESTSERVICE

# @@protoc_insertion_point(module_scope)
